name: telemetry
description: Save workflow run data to a remote endpoint or an artifact
inputs:
  endpoint:
    description: >
      The URL to an HTTP endpoint to which this action will send telemetry data. Specifically,
      if `endpoint` is a valid endpoint, `telemetry` will send a POST request the endpoint
      containing JSON-formatted telemetry data in the request body.
    required: true
  token:
    description: >
      GitHub token used to check repository content and provide feedback. By default,
      this uses the repository token provided by GitHub Actions. You can customize this
      by replacing this token with a user token which has write-access to your repository.
      Note that the token will be accessible to all repository collaborators.
    default: ${{ github.token }}
    required: false
  upstream_repo:
    description: >
      Upstream project repository name with owner. For example, dsdiscovery/microprojects.
      Fails the action if endpoint is specified but upstream_repo is not.
    required: false
  upstream_ref:
    description: >
      The branch, tag or SHA of the upstream repo. Uses the default branch if unspecified,
      or the assignment name if it is specified.
    required: false
  assignment:
    description: >
      The name of the assignment for which data is being logged. If empty, this field will not be entered.
    required: false
  meta:
    description: >
      Arbitrary metadata that gets passes directly to the telemetry endpoint, defaults to "{}".
    default: '{}'
    required: false
runs:
  using: node20
  main: ./dist/index.js
